@echo off & setlocal enableextensions

set date2=%date:~-4%_%date:~3,2%_%date:~0,2%

echo .................................................
echo ... lazy backup script because explorer sucks ...
echo .................................................

mkdir E:\Dokumente_%date2%\
xcopy C:\Users\Daniel\Documents\*.* E:\Dokumente_%date2%\ /S /Y

echo .................................................
echo ... verify filecount ............................


FOR /F "tokens=* USEBACKQ" %%F IN (`"dir C:\Users\Daniel\Documents /s /b /a:-d-h | find /c /v """`) DO (
SET filecount1=%%F
)

FOR /F "tokens=* USEBACKQ" %%F IN (`"dir E:\Dokumente_%date2%\ /s /b /a:-d-h | find /c /v """`) DO (
SET filecount2=%%F
)

echo ................................................. 
echo ... files in src folder %filecount1% ............
echo ... files in dst folder %filecount2% ............
echo .................................................
pause
